### ISSUE TITLE
Datepicker range bug

### ISSUE THREAD

**Issue by MiguelDAX** [AnnMarieW/dash-bootstrap-templates#10]
The datepicker does not display correctly when using themes. The dates above the minimum start date and maximum end date have the same style as the selected dates.
Example: https://imgur.com/a/vHnF1T0

**Comment by AnnMarieW** [comment]
Hi @MiguelDAX 
Thanks for reporting!  I'll fix that in the next release.

**Comment by AnnMarieW** [comment]
@MiguelDAX   This has been fixed now.  There may be a delay based on the caching of the stylesheet, but here's what it looks like now.  The blocked out dates are now styled with opacity to show they are not selectable.

![image](https://user-images.githubusercontent.com/72614349/189403454-c7ff14cc-fe47-4f45-b8d4-448994323c07.png)
