### ISSUE TITLE
Solarized Light Theme

### ISSUE THREAD

**Issue by LoganDGraham** [AnnMarieW/dash-bootstrap-templates#13]
Dash Bootstrap Templates is great! Would it be possible to incorporate the Solarized Light Theme?

Hexadecimal color codes are provided here:
[Solarized Webpage](https://ethanschoonover.com/solarized/).

**Comment by AnnMarieW** [comment]
I'm glad you like Dash Bootstrap Templates :slightly_smiling_face:   
The Solarized LIght Theme looks like a nice theme, but the templates in this library are created from Bootstrap stylesheets.   

You can find information on creating a figure template based on color codes in the Plotly docs here:  https://plotly.com/python/templates/
