### ISSUE TITLE
Select dark variant of a theme (data-bs-theme="dark")

### ISSUE THREAD

**Issue by jzju** [AnnMarieW/dash-bootstrap-templates#16]
Is there a way to toggle between dark and light (data-bs-theme="dark") instead of chosing a different theme with ThemeSwitchAIO?

https://getbootstrap.com/docs/5.3/customize/color-modes/

**Comment by AnnMarieW** [comment]
Hi @jzju 

This is an exciting new feature in Bootstrap 5.3 that has a lot of potential for Dash apps.

I was hoping that it would be as simple as wrapping the layout with an html.Div with  `data-bs-theme="dark"` or `data-bs-theme="light"` 

In Dash it's possible to add `data-*` props to html components, although I don't think it's documented.  It looks like this:

```
html.div(
    id="theme",
    **{"data-bs-theme": "dark"}
)
```

And it's even possible o update the `data-bs-theme` prop in a callback

```
app.callback(
    Output("theme", "data-bs-theme").
    ...
```

However it didn't work as I expected -- it only applied the dark theme to a few dbc components.  I have some ideas about how to fix it though, so I'll be working on it.  Thanks for the suggestion! :slightly_smiling_face:

**Comment by jzju** [comment]
Running this seem to work for everything except plots:

document.documentElement.setAttribute('data-bs-theme', 'dark')

**Comment by AnnMarieW** [comment]
oh, interesting. I wouldn't expect it to work with the figures, as you would still have to update the figure template in a callback. But for the rest, could you please share a complete minimal working example?

**Comment by jzju** [comment]
https://dash.plotly.com/external-resources#adding-your-own-css-and-javascript-to-dash-apps

![Screenshot_20230922_072739](https://github.com/AnnMarieW/dash-bootstrap-templates/assets/9774380/9a8562cf-ebae-41ee-b393-c693cf1fb743)

**Comment by AnnMarieW** [comment]
Hi @jzju

The latest release V1.1.0 has figure templates to match  the dark and light color modes.  See the forum post for how to use the Bootstrap color modes in a dash app.

https://community.plotly.com/t/light-and-dark-color-modes-with-dash-bootstrap-components-1-5-0/78810
