### ISSUE TITLE
Placeholder wrong color?

### ISSUE THREAD

**Issue by jzju** [AnnMarieW/dash-bootstrap-templates#20]
https://cdn.jsdelivr.net/gh/AnnMarieW/dash-bootstrap-templates@master/dbc.css

```
.dbc input::placeholder {
  color: var(--bs-body-color) !important;
  background-color: var(--bs-body-bg) !important;
}
```
```
.form-control::placeholder {
  color: var(--bs-secondary-color);
  opacity: 1;
}
```
Shoudn't the placeholder be gray insted of black?

![Screenshot_20231002_170802](https://github.com/AnnMarieW/dash-bootstrap-templates/assets/9774380/6b36842a-362b-4f94-8e4a-6e2eb1000497)

Also could the placeholder color for dbc.Input and dcc.Dropdown be synced. It seems that they are different even if it's bs-secondary-color?

```
.Select-placeholder {
  color: var(--bs-secondary-color) !important;
  background-color: var(--bs-body-bg) !important;
}
```
Seems to fix it but brobably need .dbc tags.

**Comment by AnnMarieW** [comment]
Hi @jzju 
Yes, you are correct!  Nice catch - thank you :medal_sports: 

I'll make the correction today, check tomorrow for the corrected version as it takes a bit to for the CDN to refresh.
