### ISSUE TITLE
Regression bug: Background color of graph no longer transparent

### ISSUE THREAD

**Issue by TheDurableDane** [AnnMarieW/dash-bootstrap-templates#25]
There seems to be a regression from version 1.0.8 to version 1.1.0. I have created this tiny example to show the difference:

```
#!/usr/bin/env python
from dash import Dash, html, dcc
import dash_bootstrap_components as dbc
from dash_bootstrap_templates import load_figure_template
import plotly.graph_objects as go


load_figure_template('darkly')

app = Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])

app.layout = html.Div([
    dbc.Card(
        dbc.CardBody(
            dcc.Graph(figure=go.Figure(go.Scatter(x=[1, 2, 3], y=[2, 5, 3]))),
        )
    )
])


if __name__ == '__main__':
    app.run(debug=True, port=8080)
```

When running on version 1.1.0, it looks like this:
![image](https://github.com/AnnMarieW/dash-bootstrap-templates/assets/10809595/57905ced-7b4e-4e93-90c1-4fb1c87c34ab)

But prior to this version, e.g. version 1.0.8, it looked like this:
![image](https://github.com/AnnMarieW/dash-bootstrap-templates/assets/10809595/0dde69e8-583b-44b5-94ab-38eaa337074c)

The difference might seem small, but when you add labels on the axes, titles, etc. the old version looks much better.
Do you agree that this is a regression or is it intended behavior? It there an easy fix or workaround?

**Comment by AnnMarieW** [comment]
Hi @TheDurableDane 

Thanks for reporting!  That change was not intended. I'll do an update in a few days, but in the meantime, here are a couple workarounds: 

You can update the figure template, then all the figures in your app will have the correct background color:

```python
load_figure_template('darkly')
plotly.io.templates["darkly"].layout.paper_bgcolor="#303030"

```

Or you can update it in each figure:

```python

fig=go.Figure(go.Scatter(x=[1, 2, 3], y=[2, 5, 3]))
fig.update_layout(paper_bgcolor="#303030")

dcc.Graph(figure=fig)

```

Again, thanks for letting me know - nice catch :slightly_smiling_face:
