### ISSUE TITLE
Fix typo in src/aio/aio_theme_switch.py

### ISSUE THREAD

**Issue by 3andrew** [AnnMarieW/dash-bootstrap-templates#32]
In `src/aio/aio_theme_switch.py` there's a typo in line 1 resulting in an error on install:
```
fron typing import Union
```

**Comment by AnnMarieW** [comment]
Oh, nice catch - Thank you! :pray: 

If you would like to do the PR to fix this, please do, otherwise I'll make the fix and do another release later tonight - I'd like to get this updated quickly :slightly_smiling_face:

**Comment by AnnMarieW** [comment]
closed by #33 
Thanks for the quick rix @andrew-33

**Comment by 3andrew** [comment]
Thanks for the updating quickly!
