### ISSUE TITLE
Issue with 1.2.2

### ISSUE THREAD

**Issue by louiszhuang** [AnnMarieW/dash-bootstrap-templates#34]
Attempting to connect a callback State item to component:
  "assets-url-path-store"
but no components with that id exist in the layout.

**Comment by AnnMarieW** [comment]
Hi @louiszhuang 

Thanks for reporting.  Can you include a minimal example that reproduces the issue?

**Comment by AnnMarieW** [comment]
Hi @louiszhuang 

I found the issue - fix will be ready shortly.  Thanks again for reporting!
