### ISSUE TITLE
An issue with applying some styles to checkbox

### ISSUE THREAD

**Issue by Fedorov-Artem** [AnnMarieW/dash-bootstrap-templates#39]
Hi,
I'm trying to style my dash app with dash-bootstrap-templates and got an issue with styling of Checklists.
![checklist_issue](https://github.com/user-attachments/assets/11d790a7-5a06-4a94-ae7c-3f147d82e37f)
This is how it looks when checkbox is actually selected. If I click the checkbox, dash execute the logic I've implemented, but visually nothing changes.
Style for the DatePickerRange seems working, if I click it, I see the selected dates in orange color.

Surprisingly, the style seems working if I change style to sketchy.
![checklist_issue2](https://github.com/user-attachments/assets/874374b5-c141-4e20-880c-67ca2acf2cbe)

I've only changed style from "UNITED" to "SKETCHY", checked a few times, there were no other changes.
"SANDSTONE" style doesn't work either.

```
dash_bootstrap_templates.load_figure_template('SKETCHY')

app = dash.Dash(
    __name__, external_stylesheets=[dbc.themes.SKETCHY, dbc.icons.FONT_AWESOME, dbc_css]
)
```
How is this possible?

I've included dbc and dbc-ag-grid classes for the global element.
Here is the relevant code:

```
                                    html.Div([
                                        dcc.DatePickerRange(
                                            id='time-period',
                                            min_date_allowed=str(min(df['first_online']).date()),
                                            max_date_allowed=str(max(df['first_online']).date()),
                                            start_date=str(min(df['first_online']).date()),
                                            end_date=str(max(df['first_online']).date()),
                                        ),
                                        dcc.Checklist(
                                            id="include-older",
                                            options=['include older'],
                                            value=['include older'],
                                        ),
                                    ], className='mb-4'),
```

Any suggestions?

Thank you.

**Comment by AnnMarieW** [comment]
Hi @Fedorov-Artem 

Thanks so much for reporting!  I'll get this fixed soon, but in the meantime as a workaround, you can use `dbc.Checklist` rather than `dcc.Checklist`  or you can use a previous version of the stylesheet like this:

```python
dbc_css = "https://cdn.jsdelivr.net/gh/AnnMarieW/dash-bootstrap-templates@V1.1.2/dbc.min.css"

app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP, dbc_css])

```

**Comment by Fedorov-Artem** [comment]
Hi @AnnMarieW ,
Thanks so much for answering. Yes, the workaround with `dbc.Checklist` works.

Could you please clarify, should I always use `dbc.Checklist` instead of `dcc.Checklist`? What is the difference? I can see that there are no such elements as `dbc.Dropdown` or `dbc.DatePickerRange`.

**Comment by AnnMarieW** [comment]
When the component is available and the functionality is the same, then it's better to use the dbc component because the styling is better.  

There is a `dbc.Select` which is an html Select with a Bootstrap theme, but I usually use the `dcc.Dropdown`  since it has a lot more features.  

Glad that `dbc.Checklist` works for you :tada:
