### ISSUE TITLE
Update dash-bootstrap-templates 1.0.4, update importlib-metadata to the latest version.

### ISSUE THREAD

**Issue by YoussefSultan** [AnnMarieW/dash-bootstrap-templates#7]
Error ```dash-bootstrap-templates 1.0.4 depends on importlib-metadata<4.0.0 and >=3.4.0```

I am looking to deploy an app that uses dash-bootstrap-templates however my requirements.txt requires importlib-metadata==4.2.0. & dash-bootstrap-templates is dependent on importlib=metadata<4.00. Since the requirement isn't updated to the latest version I get a build error. Looking to update the dependency of importlib-metadata to the latest version for dash-bootstrap-templates.

![](https://i.gyazo.com/4d03d2f4e978a88dd50f079619367a18.png)

**Comment by AnnMarieW** [comment]
@YoussefSultan Thanks for reporting!  I'll look into it and get back to you shortly.

**Comment by YoussefSultan** [comment]
> @YoussefSultan Thanks for reporting! I'll look into it and get back to you shortly.

I actually managed to make it work somehow by just not including dash-bootstrap-templates in the requirements.txt. Somehow the templates are loading fine on my deployment. It still may be a good idea however to update those dependencies for the future as the most recent version of importlib-metadata has some great updates in which I would assume most will have their environments updated as well.

**Comment by AnnMarieW** [comment]
Hi @YoussefSultan I'm glad you got it working!   I also just released V1.0.5 with the restriction relaxed.
