### ISSUE TITLE
Hover text font

### ISSUE THREAD

**Issue by Lxstr** [AnnMarieW/dash-bootstrap-templates#9]
Great library thanks!!

Wondering if there's a way to get the font in the figure hover text to update according to the template? Currently the remainder of the figure is correct font except for hover items.

**Comment by AnnMarieW** [comment]
Hi @Lxstr 

Nice catch - thanks,  I'll add it to the next release.  Please let me know if you find anything else missing.

Glad you like the library :slightly_smiling_face:
